In [1]:
import tensorflow as tf
import numpy as np

**Start an interactive session**

In [2]:
tf.InteractiveSession()

**Create tensors**

In [3]:
x1 = tf.constant(3.0, dtype=tf.float32)
x2 = tf.constant(np.arange(3.0), dtype=tf.float32)
x3 = tf.Variable(tf.random_normal([5, 4, 3]), name="x")

print(x1, x1.eval())
print(x2, x2.eval())
print(x3)

Tensor("Const:0", shape=(), dtype=float32) 3.0
Tensor("Const_1:0", shape=(3,), dtype=float32) [ 0.  1.  2.]
Tensor("x/read:0", shape=(5, 4, 3), dtype=float32)


** Exercise: **
1. What "eval" does?
2. What if I do not create the interactive session, can I still evaluate tensors?
3. Try to run "print x3.eval()", why x3 cannot be evaluated at this stage?

**Perform calculations**

In [4]:
a1 = tf.add(x1,x2)
a2 = tf.multiply(x1,x2)
a3 = tf.subtract(x1,x2)
a4 = tf.divide(x2,x1)

print(a1.eval())
print(a2.eval())
print(a3.eval())
print(a4.eval())

[ 3.  4.  5.]
[ 0.  3.  6.]
[ 3.  2.  1.]
[ 0.          0.33333334  0.66666669]


**More math functions**

In [5]:
a5 = tf.square(x2)
a6 = tf.pow(x2, 2)
a7 = tf.exp(x2)
a8 = tf.cos(x2)

print(a5.eval())
print(a6.eval())
print(a7.eval())
print(a8.eval())

[ 0.  1.  4.]
[ 0.  1.  4.]
[ 1.          2.71828175  7.38905621]
[ 1.          0.54030228 -0.41614684]


**Deal with matrices**

In [6]:
x1 = tf.constant(np.random.randn(4,3), tf.float32) # create a matrix of shape (4,3)
x2 = tf.constant(np.random.randn(3,4), tf.float32) # create a matrix of shape (3,4)

print(x1.get_shape())
print(x2.get_shape())

a1 = tf.transpose(x1) # transpose the matrix
a2 = tf.matmul(x1, x2) # perform the multiplication

print(a1.get_shape(), a1.eval())
print(a2.get_shape(), a2.eval())

(4, 3)
(3, 4)
(3, 4) [[-0.18618293  1.1549269   2.58715439 -0.55028504]
 [ 0.02782409  0.23713699  0.20510338 -0.41397518]
 [-0.20827243 -0.24975823  0.847987   -0.53563541]]
(4, 4) [[ 0.37944287  0.3089734  -0.04486424  0.48277754]
 [-1.05541635 -0.88347697 -0.37227154 -1.56395483]
 [-3.61655402 -2.9084084  -0.2199347  -4.87001753]
 [ 1.71806717  0.72240251 -0.29762328  1.9507823 ]]


For more math operations, please refer to https://www.tensorflow.org/api_guides/python/math_ops